### ISSUE TITLE
limitation period 

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#164]
### Problem details

It happens that the bot incorrectly sets other dates.  in the config file, a period of 1 day is set, and it blocks for 1 year, forever, and so on.  Is it possible to set an additional check for the limitation period?
![6D746035-6BCD-4F2D-9089-26E75B160E22](https://user-images.githubusercontent.com/44323817/196630085-2d1e7170-b000-4a21-aa53-8c3256e9cedc.jpeg)

### Steps to reproduce

1 entering the chat of a new member
2 imposition by the bot of an incorrect period for blocking actions

### Expected behavior

There should have been a 1 day limit. 

### Actual behavior

The screenshot has a 365 day limit.

### Project version

1.7.0

### Platform

Microsoft Windows

### OS version

Windows 10

### Python version

.Exe

### Installation type

EXE installer

**Comment by xvitaly** [comment]
Did you used `/restrict 1`?

**Comment by vlab97** [comment]
> Did you used /restrict 1?

No.  Automatic restriction for new chat participants is used.

Can we switch to Russian?  😁

**Comment by vlab97** [comment]
"bantime": 86400,

**Comment by xvitaly** [comment]
> Can we switch to Russian?

OK.

> "bantime": 86400,

Если никнейм пользователя [набирает](https://github.com/xvitaly/ecasbot/blob/f4c06c1cfafe33c5d04f935f7f8b72f64b756f52/ecasbot/__init__.py#L719) больше баллов, чем указано в [nickgoal](https://github.com/xvitaly/ecasbot/blob/master/packaging/assets/ecasbot.json#L12), делённое на 2, то пользователь ограничивается на 366 дней (максимум для Telegram Bot API).

Т.е. можно просто `nickgoal` изменить с 100 до 200 например, либо использовать любое другое желаемое значение.

**Comment by vlab97** [comment]
> > Can we switch to Russian?
> 
> OK.
> 
> > "bantime": 86400,
> 
> Если никнейм пользователя [набирает](https://github.com/xvitaly/ecasbot/blob/f4c06c1cfafe33c5d04f935f7f8b72f64b756f52/ecasbot/__init__.py#L719) больше баллов, чем указано в [nickgoal](https://github.com/xvitaly/ecasbot/blob/master/packaging/assets/ecasbot.json#L12), делённое на 2, то его аккаунт ограничивается на 366 дней (максимум для Telegram Bot API).
> 
> Т.е. можно просто `nickgoal` изменить с 100 до 200 например, либо использовать любое другое желаемое значение.

В консоли ник набрал 50 баллов
INFO:ecasbot:Новый пользователь Игорь (-) вступил в чат - - (-). Баллы: 50.

nickgoal был выставлен на 100, по вашему совету увеличу значение в 2 раза. А дальше посмотрим. Спасибо

Просто странно, что даже по логу ник набрал 50/100 баллов и ушел в максимальную блокировку по сроку

**Comment by xvitaly** [comment]
> То есть если админ анонимен, то команды /mute и прочее не работают для него.

Логично ибо через Telegram Bot API нельзя определить администратора, который инициировал данное действие. Это можно достаточно легко исправить если в функцию проверки действий добавить и собственный ID чата, но нужно проверить для начала не будет ли это являться угрозой безопасности. Создал новый тикет #165 по данной проблеме.
