### ISSUE TITLE
LOG File

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#167]
### Question

Как правильно подключить ведение отчета в Log файл?

**Comment by vlab97** [comment]
Пытался использовать логирование в файл, но вылетала ошибка с кодировкой
UnicodeEncodeError: 'charmap' codec can't encode character '\u3164' in position 60: character maps to <undefined>

**Comment by xvitaly** [comment]
> Как правильно подключить ведение отчета в Log файл?

Указать полный путь к файлу журнала в параметре `logtofile` конфига бота.

> Пытался использовать логирование в файл, но вылетала ошибка с кодировкой

Файл должен существовать и иметь правильные права доступа (как минимум иметь доступ на запись для пользователя, от имени которого выполняется бот).

**Comment by vlab97** [comment]
При вводе команды /ent_list вылетает ошибка записи в лог 

--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
  File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u3164' in position 60: character maps to <undefined>
Call stack:
  File "threading.py", line 966, in _bootstrap
  File "threading.py", line 1009, in _bootstrap_inner
  File "telebot\util.py", line 98, in run
  File "ecasbot\__init__.py", line 440, in __handle_entlist
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1209, in emit
  File "logging\__init__.py", line 1106, in emit
Message: 'Администратор ㅤ (id администратора) запросил вывод списка типов запрещённого контента.'
Arguments: ()

**Comment by vlab97** [comment]
/sw_list так же с ошибкой при записи лога

**Comment by xvitaly** [comment]
> В имени аккаунта используется символ, который не отображается. Возможно из-за этого.

Лучше избегать нелатинских символов в путях.

**Comment by vlab97** [comment]
> > В имени аккаунта используется символ, который не отображается. Возможно из-за этого.
> 
> Лучше избегать нелатинских символов в путях.

В пути все латинское. В самом Telegram имя администратора не отображается.(пустое). То есть используется символ U+3164 в имени администратора. При выводе в коммандную строку проблем нет, а при записи в файл ошибка кодировки.

**Comment by xvitaly** [comment]
> То есть используется символ U+3164 в имени администратора. При выводе в коммандную строку проблем нет, а при записи в файл ошибка кодировки.

Понял, спасибо за сообщение об ошибке. Потеряли параметр кодировки при открытии журнала. В Windows используется cp1251 вместо utf-8, как в Linux. Постараюсь сегодня исправить.

**Comment by xvitaly** [comment]
Исправлено в [версии 1.7.1](https://github.com/xvitaly/ecasbot/releases/tag/v1.7.1).
