### ISSUE TITLE
Permission Bug

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#192]
### Problem details

Сегодня заметил, что бот редактирует уже имеющиеся ограничения на пользователях. То есть перезаход в чат снимает наложенные ограничения…

### Steps to reproduce

1 наложить ограничения навсегда админом 
2 выйти аккаунтом с чата 
3 войти обратно в чат
4 бот накладывает свои ограничения, заменив уже имеющиеся 

### Expected behavior

бот редактирует уже имеющиеся ограничения на пользователях.

### Actual behavior

При наличии ограничений, бот пропускает лак с наложением ограничений от себя 

### Project version

1.7.1

### Platform

Microsoft Windows

### OS version

Windows 10

### Python version

Python 10

### Installation type

EXE installer

**Comment by vlab97** [comment]
![08A52256-234D-4FEB-B3DF-A70554773203](https://user-images.githubusercontent.com/44323817/212812924-5adc6035-c41a-461c-8e80-33ee043267b1.jpeg)

**Comment by xvitaly** [comment]
Интересный баг, благодарю за сообщение о нём. В наших чатах обычно сразу банили без отправления в бессрочный r/o, поэтому его никто и не замечал.

Постараемся починить в ближайшее время.

**Comment by vlab97** [comment]
> Исправлено.

Спасибо. Так же команда /un снимает не все ограничения. 
Остаются ограничения:
Send pools 
Add members 
Pin messages 
Manage topics
Change info

На пользователя сначала накладывались /mute 1, а затем /un. 

/mute 1:

changed restrictions for Mex (@user)
until Thu, 19 Jan 09:00

-Send Messages
-Send Media
-Send Stickers & GIFs
-Embed Links
-Send Polls
-Add Members
-Pin Messages
-Manage Topics
-Change Info

/un:

changed restrictions for Mex (@user)
indefinitely

+Send Messages
+Send Media
+Send Stickers & GIFs
+Embed Links

**Comment by xvitaly** [comment]
> Спасибо. Так же команда /un снимает не все ограничения.

Интересно, спасибо. Сейчас также исправлю.

**Comment by xvitaly** [comment]
Исправлено.
