### ISSUE TITLE
stop list text encoding

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#207]
### Problem details

В .json файле кириллица отображается в неверной кодировке. На работу бота не влияет, но через Json проблематично редактировать слова 

### Steps to reproduce

1. Добавить запрещенное слово командой 
2. Открыть .json файл конфигурации

### Expected behavior

Отображение кириллицы в .json

### Actual behavior

Отображение кириллицы в unicode escape sequence

### Project version

1.8.1

### Platform

Microsoft Windows

### OS version

Windows 11

### Python version

3.11

### Installation type

EXE installer

**Comment by vlab97** [comment]
![Без имени](https://user-images.githubusercontent.com/44323817/227887129-e4ae1a21-4edb-45a1-aff9-98942e5a3e7a.png)

**Comment by xvitaly** [comment]
Это стандартная сериализация юникода в Python. Все non-ASCII символы превращаются и сохраняются как последовательность байтов для корректной десериализации.

От платформы, на которой запущен Python, это не зависит.
