### ISSUE TITLE
checking BIO for spam

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#208]
### Feature request

Стал замечать, что заходят новые пользователи со ссылкой в BIO на сайты с запрещенными веществами и прочим. После входа в чат они здороваются со всеми. На скриншотах приведу примеры. Как пример создать отдельную проверку со своим стоп листом. В первом случае ссылка ведет на сторонний сайт. Во втором случае ссылка ведет сначала на telegraph с информацией и всеми ссылками.
![Снимок экрана 2023-03-28 074728](https://user-images.githubusercontent.com/44323817/228131854-5dce5589-adc6-41ce-97ba-a1fcfdcff4d6.png)
![Снимок экрана 2023-03-28 074816](https://user-images.githubusercontent.com/44323817/228131857-e046e18a-5676-4e9c-83ab-61333c22bd33.png)
![Снимок экрана 2023-03-28 075022](https://user-images.githubusercontent.com/44323817/228131859-c5f2a16b-f3d4-46a5-a101-86c2dd5ba7fc.png)

**Comment by xvitaly** [comment]
Такое уже запрашивали в #33, однако в Bot API не было механизмов чтения BIO. Нужно проверить не добавили ли их в актуальных версиях Bot API.

**Comment by xvitaly** [comment]
Проверил, в Bot API до сих пор нет метода получения BIO. Объект `User` возвращает лишь [это](https://core.telegram.org/bots/api#user).

В текущем API значение BIO можно получить лишь двумя путями:
1. Через [объект Chat](https://core.telegram.org/bots/api#chat), который доступен лишь для приватного чата с ботом. Очевидно, что спамер не станет писать в ЛС боту, а бот первым написать не может из-за ограничений со стороны Telegram.
2. Через [объект ChatJoinRequest](https://core.telegram.org/bots/api#chatjoinrequest) если включен вход в чат только по приглашениям и юзер отправил заявку на вступление.
