### ISSUE TITLE
Сообщение, содержащее только emoji 

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#209]
### Question

Люди бывают реагируют на сообщение отправкой смайла в ответ, бот удаляет такие сообщения. Возможно это отключить?

**Comment by xvitaly** [comment]
Бот устанавливает +100 к сообщениям, содержащим только emoji без какого-либо текста в функции `check_emoji_bot`: https://github.com/xvitaly/ecasbot/blob/master/src/ecasbot/chkmsg.py#L28-L33

**Comment by vlab97** [comment]
Странно, что я выставляю значение на 0 или вообще вырезаю функцию. Один фиг происходит удаление

**Comment by xvitaly** [comment]
> Странно, что я выставляю значение на 0 или вообще вырезаю функцию. Один фиг происходит удаление

Возможно, что сообщение набирает и без этого метода больше, чем указано в конфиге для удаления. Можно включить режим дебага и тогда в логах будет указан score каждого удаляемого сообщения.

**Comment by xvitaly** [comment]
Создал issue #210, чтобы разрешить указывать свои коэффициенты для функций в конфиге.

**Comment by vlab97** [comment]
> > Странно, что я выставляю значение на 0 или вообще вырезаю функцию. Один фиг происходит удаление
> 
> Возможно, что сообщение набирает и без этого метода больше, чем указано в конфиге для удаления. Можно включить режим дебага и тогда в логах будет указан score каждого удаляемого сообщения.

Перепроверил, метод работает. Инсталлятор просто закидывал исполняемые файлы в другую папку ...
