### ISSUE TITLE
Отсутствие сервисных сообщений 

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#213]
### Question

В одном из чатов перестали появляться сервисные сообщения о входе пользователей. То есть в недавних действиях они есть, а в самом чате их нет. Соотвественно бот стал бесполезен. Пользователи при этом в чате не скрыты. Возможно сделать альтернативный режим работы у бота? Чтоб к примеру был у бота стоп лист не зависящий от ограничений пользователя.

**Comment by xvitaly** [comment]
> В одном из чатов перестали появляться сервисные сообщения о входе пользователей. То есть в недавних действиях они есть, а в самом чате их нет.

Видимо это не супергруппа. Bot API нормально работает только в супергруппах.

> Возможно сделать альтернативный режим работы у бота? Чтоб к примеру был у бота стоп лист не зависящий от ограничений пользователя.

В версии 2.x мы так и хотели сделать, но для этого потребуется сервер СУБД. В базу данных будут дублироваться все без исключения сообщения и действия в чате. В таком случае будет можно выполнять более сложные проверки при помощи SQL-запросов и не зависеть от ограничений Telegram.

**Comment by vlab97** [comment]
> > В одном из чатов перестали появляться сервисные сообщения о входе пользователей. То есть в недавних действиях они есть, а в самом чате их нет.
> 
> Видимо это не супергруппа. Bot API нормально работает только в супергруппах.
> 
> > Возможно сделать альтернативный режим работы у бота? Чтоб к примеру был у бота стоп лист не зависящий от ограничений пользователя.
> 
> В версии 2.x мы так и хотели сделать, но для этого потребуется сервер СУБД. В базу данных будут дублироваться все без исключения сообщения и действия в чате. В таком случае будет можно выполнять более сложные проверки при помощи SQL-запросов и не зависеть от ограничений Telegram.

супергруппа. С недавнего времени появилась такая проблема

**Comment by xvitaly** [comment]
> супергруппа. С недавнего времени появилась такая проблема

Если Telegram перестал информировать через Bot API о новых событиях в группах, то это очень плохо, причём для любых ботов. Жаль, что у них нет даже техподдержки, в которой бы можно было точно узнать подробности. В официальном блоге никаких заявлений об изменениях в API не было.

**Comment by vlab97** [comment]
Он временами информирует. Странно...![image](https://github.com/xvitaly/ecasbot/assets/44323817/09c0f0a4-67f5-4457-a955-6a7b70ad5c5e)

**Comment by xvitaly** [comment]
> Он временами информирует. Странно.

Видимо какие-то проблемы в самом Telegram. В любом случае, со стороны бота с этим ничего сделать нельзя.
